version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    platform: linux/amd64
    environment:
      SA_PASSWORD: n0m3l0s3.
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      MSSQL_TCP_PORT: 1433