 — SQL Server script
USE master;
GO

- Drop the database if it exists
IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'DEA')
 DROP DATABASE DEA;
GO
 - Create the database
CREATE DATABASE DEA;
GO
USE DEA;
GO

CREATE TABLE DEPARTMENT (
	DEPT_ID			INTEGER			PRIMARY KEY,
    DEPT_NM			VARCHAR(50),
    DATE_CREATED	DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    DATE_UPDATED	DATETIME2
);

CREATE TABLE POSITIONS (
	POS_ID			INTEGER			PRIMARY KEY,
    POS_NM			VARCHAR(100),
    DATE_CREATED	DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    DATE_UPDATED	DATETIME2
);

CREATE TABLE EMPLOYEE (
	EMP_ID		INTEGER			PRIMARY KEY,
    DEPT_ID 	INTEGER,
    POS_ID  	INTEGER,
    LAST_NAME	VARCHAR(100),
    FIRST_NAME	VARCHAR(100),
    EMAIL		VARCHAR(100),
    MANAGER_ID	INTEGER,
    DATE_CREATED	DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    DATE_UPDATED	DATETIME2,
    CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID),
    CONSTRAINT EMP_POS_FK FOREIGN KEY (POS_ID) REFERENCES POSITIONS(POS_ID)
);

CREATE TABLE SALARY(
	SAL_ID			INTEGER		PRIMARY KEY,
    EMP_ID			INTEGER,
    SALARY_PER_HR	FLOAT,
    TAX				FLOAT,
    DATE_CREATED	DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    DATE_UPDATED	DATETIME2,
    CONSTRAINT SAL_EMP_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);